export const IPC = {
  LOAD_SESSIONS: 'sessions:load',
  SAVE_SESSIONS: 'sessions:save',
  LOAD_SETTINGS: 'settings:load',
  SAVE_SETTINGS: 'settings:save',
  LIST_CLAUDE_SESSIONS: 'claude:list-sessions',
  PICK_FOLDER: 'dialog:pick-folder',
  OPEN_EXTERNAL: 'shell:open-external',
  OPEN_PATH: 'shell:open-path',
  LOCAL_PTY_SPAWN: 'pty:spawn',
  LOCAL_PTY_INPUT: 'pty:input',
  LOCAL_PTY_RESIZE: 'pty:resize',
  LOCAL_PTY_KILL: 'pty:kill',
  LOCAL_PTY_OUTPUT: 'pty:output',
  LOCAL_PTY_EXIT: 'pty:exit',
  CLAUDE_SESSION_DETECTED: 'claude:session-detected',
  TOOL_SESSION_DETECTED: 'tool:session-detected',
  FILE_DROP: 'file:drop',
  SET_ACTIVE_SESSION: 'session:set-active'
} as const
